name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: jdx/mise-action@v2
      - run: mise run install
      - run: mise run check
      - run: mise run build
      - run: mise run attw

  test:
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run install
      - run: mise run test-coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          comment-on: "pr"
